using Design.ORiN3.Common.V1;
using Message.ORiN3.Provider.V1.AutoGenerated;
using System;
using System.Linq;

namespace Message.ORiN3.Provider.V1.Branch;

public class ORiN3ValueToCSharpValueBranch<T> : IValueTypeBranch
{
    public ORiN3Value Target { get; set; }

    public T Result { get; private set; }

#pragma warning disable CS8618
    public ORiN3ValueToCSharpValueBranch(ORiN3Value target)
#pragma warning restore CS8618
    {
        Target = target;
    }

    public void CaseOfBool()
    {
        Result = (T)(object)Target.Bool.RawValue;
    }

    public void CaseOfBoolArray()
    {
        Result = (T)(object)Target.BoolArray.RawValue.ToArray();
    }

    public void CaseOfNullableBool()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableBool.IsNull ? null : Target.NullableBool.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableBoolArray()
    {
        Result = (T)(object)Target.NullableBoolArray.RawValue.Select(_ => _.IsNull ? null : (bool?)_.RawValue).ToArray();
    }

    public void CaseOfInt8()
    {
        Result = (T)(object)(sbyte)Target.Int8.RawValue;
    }

    public void CaseOfInt8Array()
    {
        Result = (T)(object)Target.Int8Array.RawValue.Select(_ => (sbyte)_).ToArray();
    }

    public void CaseOfNullableInt8()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableInt8.IsNull ? null : (sbyte?)Target.NullableInt8.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableInt8Array()
    {
        Result = (T)(object)Target.NullableInt8Array.RawValue.Select(_ => _.IsNull ? null : (sbyte?)_.RawValue).ToArray();
    }

    public void CaseOfInt16()
    {
        Result = (T)(object)(short)Target.Int16.RawValue;
    }

    public void CaseOfInt16Array()
    {
        Result = (T)(object)Target.Int16Array.RawValue.Select(_ => (short)_).ToArray();
    }

    public void CaseOfNullableInt16()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableInt16.IsNull ? null : (short?)Target.NullableInt16.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableInt16Array()
    {
        Result = (T)(object)Target.NullableInt16Array.RawValue.Select(_ => _.IsNull ? null : (short?)_.RawValue).ToArray();
    }

    public void CaseOfInt32()
    {
        Result = (T)(object)Target.Int32.RawValue;
    }

    public void CaseOfInt32Array()
    {
        Result = (T)(object)Target.Int32Array.RawValue.ToArray();
    }

    public void CaseOfNullableInt32()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableInt32.IsNull ? null : Target.NullableInt32.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableInt32Array()
    {
        Result = (T)(object)Target.NullableInt32Array.RawValue.Select(_ => _.IsNull ? null : (int?)_.RawValue).ToArray();
    }

    public void CaseOfInt64()
    {
        Result = (T)(object)Target.Int64.RawValue;
    }

    public void CaseOfInt64Array()
    {
        Result = (T)(object)Target.Int64Array.RawValue.ToArray();
    }

    public void CaseOfNullableInt64()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableInt64.IsNull ? null : Target.NullableInt64.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableInt64Array()
    {
        Result = (T)(object)Target.NullableInt64Array.RawValue.Select(_ => _.IsNull ? null : (long?)_.RawValue).ToArray();
    }

    public void CaseOfUInt8()
    {
        Result = (T)(object)(byte)Target.Uint8.RawValue;
    }

    public void CaseOfUInt8Array()
    {
        Result = (T)(object)Target.Uint8Array.RawValue.Select(_ => (byte)_).ToArray();
    }

    public void CaseOfNullableUInt8()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableUint8.IsNull ? null : (byte?)Target.NullableUint8.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableUInt8Array()
    {
        Result = (T)(object)Target.NullableUint8Array.RawValue.Select(_ => _.IsNull ? null : (byte?)_.RawValue).ToArray();
    }

    public void CaseOfUInt16()
    {
        Result = (T)(object)(ushort)Target.Uint16.RawValue;
    }

    public void CaseOfUInt16Array()
    {
        Result = (T)(object)Target.Uint16Array.RawValue.Select(_ => (ushort)_).ToArray();
    }

    public void CaseOfNullableUInt16()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableUint16.IsNull ? null : (ushort?)Target.NullableUint16.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableUInt16Array()
    {
        Result = (T)(object)Target.NullableUint16Array.RawValue.Select(_ => _.IsNull ? null : (ushort?)_.RawValue).ToArray();
    }

    public void CaseOfUInt32()
    {
        Result = (T)(object)Target.Uint32.RawValue;
    }

    public void CaseOfUInt32Array()
    {
        Result = (T)(object)Target.Uint32Array.RawValue.ToArray();
    }

    public void CaseOfNullableUInt32()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableUint32.IsNull ? null : Target.NullableUint32.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableUInt32Array()
    {
        Result = (T)(object)Target.NullableUint32Array.RawValue.Select(_ => _.IsNull ? null : (uint?)_.RawValue).ToArray();
    }

    public void CaseOfUInt64()
    {
        Result = (T)(object)Target.Uint64.RawValue;
    }

    public void CaseOfUInt64Array()
    {
        Result = (T)(object)Target.Uint64Array.RawValue.ToArray();
    }

    public void CaseOfNullableUInt64()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableUint64.IsNull ? null : Target.NullableUint64.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableUInt64Array()
    {
        Result = (T)(object)Target.NullableUint64Array.RawValue.Select(_ => _.IsNull ? null : (ulong?)_.RawValue).ToArray();
    }

    public void CaseOfFloat()
    {
        Result = (T)(object)Target.Float.RawValue;
    }

    public void CaseOfFloatArray()
    {
        Result = (T)(object)Target.FloatArray.RawValue.ToArray();
    }

    public void CaseOfNullableFloat()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableFloat.IsNull ? null : Target.NullableFloat.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableFloatArray()
    {
        Result = (T)(object)Target.NullableFloatArray.RawValue.Select(_ => _.IsNull ? null : (float?)_.RawValue).ToArray();
    }

    public void CaseOfDouble()
    {
        Result = (T)(object)Target.Double.RawValue;
    }

    public void CaseOfDoubleArray()
    {
        Result = (T)(object)Target.DoubleArray.RawValue.ToArray();
    }

    public void CaseOfNullableDouble()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableDouble.IsNull ? null : Target.NullableDouble.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableDoubleArray()
    {
        Result = (T)(object)Target.NullableDoubleArray.RawValue.Select(_ => _.IsNull ? null : (double?)_.RawValue).ToArray();
    }

    public void CaseOfString()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.String.IsNull ? null : Target.String.RawValue);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfStringArray()
    {
        Result = (T)(object)Target.StringArray.RawValue.Select(_ => _.IsNull ? null : (string)_.RawValue).ToArray();
    }

    public void CaseOfDateTime()
    {
        Result = (T)(object)DateTime.FromBinary(Target.Datetime.RawValue);
    }

    public void CaseOfDateTimeArray()
    {
        Result = (T)(object)Target.DatetimeArray.RawValue.Select(_ => DateTime.FromBinary(_)).ToArray();
    }

    public void CaseOfNullableDateTime()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)(Target.NullableDatetime.IsNull ? null : DateTime.FromBinary(Target.NullableDatetime.RawValue));
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfNullableDateTimeArray()
    {
        Result = (T)(object)Target.NullableDatetimeArray.RawValue.Select(_ => _.IsNull ? null : (DateTime?)DateTime.FromBinary(_.RawValue)).ToArray();
    }

    public void CaseOfObject()
    {
#pragma warning disable CS8600
#pragma warning disable CS8601
        Result = (T)(object)ORiN3BinaryConverter.ToObject(Target.Object.RawValue.Span);
#pragma warning restore CS8601
#pragma warning restore CS8600
    }

    public void CaseOfError()
    {
        throw new InvalidOperationException();
    }
}
