using Message.ORiN3.Common.V1.AutoGenerated;
using System;

namespace Message.ORiN3.Common.V1.Branch.Switcher;

/// <summary>
/// The exception throwen by TypeSwitcher.
/// </summary>
public sealed class TypeSwitcherException : ApplicationException
{
    internal TypeSwitcherException(ORiN3Value.ValueOneofCase type, Exception innerException)
        : base($"An exception occurred during the execution of the process. See Inner Exceptions for details. [Type={type}]", innerException)
    {
    }

    internal TypeSwitcherException(Type type, Exception innerException)
        : base($"An exception occurred during the execution of the process. See Inner Exceptions for details. [Type={type.Name}]", innerException)
    {
    }

    internal TypeSwitcherException(Design.ORiN3.Provider.V1.Type.ORiN3ValueType type, Exception innerException)
        : base($"An exception occurred during the execution of the process. See Inner Exceptions for details. [Type={type}]", innerException)
    {
    }
}
