using Design.ORiN3.Common.V1;
using Design.ORiN3.Provider.V1.Type;
using Message.ORiN3.Common.V1.AutoGenerated;
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;

namespace Message.ORiN3.Common.V1.Branch.Switcher;

/// <summary>
/// The class which provides the functions of action determination by type.
/// </summary>
public static class TypeSwitcher
{
    /// <summary>
    /// Execute an action determination by ValueOneofCase.
    /// The action is provided by the branch.
    /// </summary>
    /// <param name="type"></param>
    /// <param name="branch"></param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="TypeSwitcherException"></exception>
    [DebuggerStepThrough]
    public static void Execute(ORiN3Value.ValueOneofCase type, IValueTypeBranch branch)
    {
        branch = branch ?? throw new ArgumentNullException(nameof(branch));

        try
        {
            switch (type)
            {
                case ORiN3Value.ValueOneofCase.Bool:
                    branch.CaseOfBool();
                    return;
                case ORiN3Value.ValueOneofCase.BoolArray:
                    branch.CaseOfBoolArray();
                    return;
                case ORiN3Value.ValueOneofCase.NullableBool:
                    branch.CaseOfNullableBool();
                    return;
                case ORiN3Value.ValueOneofCase.NullableBoolArray:
                    branch.CaseOfNullableBoolArray();
                    return;
                case ORiN3Value.ValueOneofCase.UInt8:
                    branch.CaseOfUInt8();
                    return;
                case ORiN3Value.ValueOneofCase.UInt8Array:
                    branch.CaseOfUInt8Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt8:
                    branch.CaseOfNullableUInt8();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt8Array:
                    branch.CaseOfNullableUInt8Array();
                    return;
                case ORiN3Value.ValueOneofCase.UInt16:
                    branch.CaseOfUInt16();
                    return;
                case ORiN3Value.ValueOneofCase.UInt16Array:
                    branch.CaseOfUInt16Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt16:
                    branch.CaseOfNullableUInt16();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt16Array:
                    branch.CaseOfNullableUInt16Array();
                    return;
                case ORiN3Value.ValueOneofCase.UInt32:
                    branch.CaseOfUInt32();
                    return;
                case ORiN3Value.ValueOneofCase.UInt32Array:
                    branch.CaseOfUInt32Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt32:
                    branch.CaseOfNullableUInt32();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt32Array:
                    branch.CaseOfNullableUInt32Array();
                    return;
                case ORiN3Value.ValueOneofCase.UInt64:
                    branch.CaseOfUInt64();
                    return;
                case ORiN3Value.ValueOneofCase.UInt64Array:
                    branch.CaseOfUInt64Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt64:
                    branch.CaseOfNullableUInt64();
                    return;
                case ORiN3Value.ValueOneofCase.NullableUInt64Array:
                    branch.CaseOfNullableUInt64Array();
                    return;
                case ORiN3Value.ValueOneofCase.Int8:
                    branch.CaseOfInt8();
                    return;
                case ORiN3Value.ValueOneofCase.Int8Array:
                    branch.CaseOfInt8Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt8:
                    branch.CaseOfNullableInt8();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt8Array:
                    branch.CaseOfNullableInt8Array();
                    return;
                case ORiN3Value.ValueOneofCase.Int16:
                    branch.CaseOfInt16();
                    return;
                case ORiN3Value.ValueOneofCase.Int16Array:
                    branch.CaseOfInt16Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt16:
                    branch.CaseOfNullableInt16();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt16Array:
                    branch.CaseOfNullableInt16Array();
                    return;
                case ORiN3Value.ValueOneofCase.Int32:
                    branch.CaseOfInt32();
                    return;
                case ORiN3Value.ValueOneofCase.Int32Array:
                    branch.CaseOfInt32Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt32:
                    branch.CaseOfNullableInt32();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt32Array:
                    branch.CaseOfNullableInt32Array();
                    return;
                case ORiN3Value.ValueOneofCase.Int64:
                    branch.CaseOfInt64();
                    return;
                case ORiN3Value.ValueOneofCase.Int64Array:
                    branch.CaseOfInt64Array();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt64:
                    branch.CaseOfNullableInt64();
                    return;
                case ORiN3Value.ValueOneofCase.NullableInt64Array:
                    branch.CaseOfNullableInt64Array();
                    return;
                case ORiN3Value.ValueOneofCase.Float:
                    branch.CaseOfFloat();
                    return;
                case ORiN3Value.ValueOneofCase.FloatArray:
                    branch.CaseOfFloatArray();
                    return;
                case ORiN3Value.ValueOneofCase.NullableFloat:
                    branch.CaseOfNullableFloat();
                    return;
                case ORiN3Value.ValueOneofCase.NullableFloatArray:
                    branch.CaseOfNullableFloatArray();
                    return;
                case ORiN3Value.ValueOneofCase.Double:
                    branch.CaseOfDouble();
                    return;
                case ORiN3Value.ValueOneofCase.DoubleArray:
                    branch.CaseOfDoubleArray();
                    return;
                case ORiN3Value.ValueOneofCase.NullableDouble:
                    branch.CaseOfNullableDouble();
                    return;
                case ORiN3Value.ValueOneofCase.NullableDoubleArray:
                    branch.CaseOfNullableDoubleArray();
                    return;
                case ORiN3Value.ValueOneofCase.String:
                    branch.CaseOfString();
                    return;
                case ORiN3Value.ValueOneofCase.StringArray:
                    branch.CaseOfStringArray();
                    return;
                case ORiN3Value.ValueOneofCase.DateTime:
                    branch.CaseOfDateTime();
                    return;
                case ORiN3Value.ValueOneofCase.DateTimeArray:
                    branch.CaseOfDateTimeArray();
                    return;
                case ORiN3Value.ValueOneofCase.NullableDateTime:
                    branch.CaseOfNullableDateTime();
                    return;
                case ORiN3Value.ValueOneofCase.NullableDateTimeArray:
                    branch.CaseOfNullableDateTimeArray();
                    return;
                case ORiN3Value.ValueOneofCase.Object:
                    branch.CaseOfObject();
                    return;
                default:
                    branch.CaseOfError();
                    return;
            }
        }
        catch (Exception e)
        {
            throw new TypeSwitcherException(type, e);
        }
    }

    /// <summary>
    /// Execute an action determination by type.
    /// The action is provided by the branch.
    /// </summary>
    /// <param name="type"></param>
    /// <param name="branch"></param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="TypeSwitcherException"></exception>
    [DebuggerStepThrough]
    public static void Execute(Type type, IValueTypeBranch branch)
    {
        type = type ?? throw new ArgumentNullException(nameof(type));
        branch = branch ?? throw new ArgumentNullException(nameof(branch));

        try
        {
            switch (Type.GetTypeCode(type))
            {
                case TypeCode.Boolean:
                    branch.CaseOfBool();
                    return;
                case TypeCode.Byte:
                    branch.CaseOfUInt8();
                    return;
                case TypeCode.UInt16:
                    branch.CaseOfUInt16();
                    return;
                case TypeCode.UInt32:
                    branch.CaseOfUInt32();
                    return;
                case TypeCode.UInt64:
                    branch.CaseOfUInt64();
                    return;
                case TypeCode.SByte:
                    branch.CaseOfInt8();
                    return;
                case TypeCode.Int16:
                    branch.CaseOfInt16();
                    return;
                case TypeCode.Int32:
                    branch.CaseOfInt32();
                    return;
                case TypeCode.Int64:
                    branch.CaseOfInt64();
                    return;
                case TypeCode.Single:
                    branch.CaseOfFloat();
                    return;
                case TypeCode.Double:
                    branch.CaseOfDouble();
                    return;
                case TypeCode.String:
                    branch.CaseOfString();
                    return;
                case TypeCode.DateTime:
                    branch.CaseOfDateTime();
                    return;
                default:
                    if (type.IsArray)
                    {
                        switch (Type.GetTypeCode(type.GetElementType()))
                        {
                            case TypeCode.Boolean:
                                branch.CaseOfBoolArray();
                                return;
                            case TypeCode.Byte:
                                branch.CaseOfUInt8Array();
                                return;
                            case TypeCode.UInt16:
                                branch.CaseOfUInt16Array();
                                return;
                            case TypeCode.UInt32:
                                branch.CaseOfUInt32Array();
                                return;
                            case TypeCode.UInt64:
                                branch.CaseOfUInt64Array();
                                return;
                            case TypeCode.SByte:
                                branch.CaseOfInt8Array();
                                return;
                            case TypeCode.Int16:
                                branch.CaseOfInt16Array();
                                return;
                            case TypeCode.Int32:
                                branch.CaseOfInt32Array();
                                return;
                            case TypeCode.Int64:
                                branch.CaseOfInt64Array();
                                return;
                            case TypeCode.Single:
                                branch.CaseOfFloatArray();
                                return;
                            case TypeCode.Double:
                                branch.CaseOfDoubleArray();
                                return;
                            case TypeCode.String:
                                branch.CaseOfStringArray();
                                return;
                            case TypeCode.DateTime:
                                branch.CaseOfDateTimeArray();
                                return;
                            case TypeCode.Object:
                                if (type.GetElementType().GenericTypeArguments.Length == 0)
                                {
                                    branch.CaseOfObject();
                                    return;
                                }
                                switch (Type.GetTypeCode(type.GetElementType().GenericTypeArguments[0]))
                                {
                                    case TypeCode.Boolean:
                                        branch.CaseOfNullableBoolArray();
                                        return;
                                    case TypeCode.Byte:
                                        branch.CaseOfNullableUInt8Array();
                                        return;
                                    case TypeCode.UInt16:
                                        branch.CaseOfNullableUInt16Array();
                                        return;
                                    case TypeCode.UInt32:
                                        branch.CaseOfNullableUInt32Array();
                                        return;
                                    case TypeCode.UInt64:
                                        branch.CaseOfNullableUInt64Array();
                                        return;
                                    case TypeCode.SByte:
                                        branch.CaseOfNullableInt8Array();
                                        return;
                                    case TypeCode.Int16:
                                        branch.CaseOfNullableInt16Array();
                                        return;
                                    case TypeCode.Int32:
                                        branch.CaseOfNullableInt32Array();
                                        return;
                                    case TypeCode.Int64:
                                        branch.CaseOfNullableInt64Array();
                                        return;
                                    case TypeCode.Single:
                                        branch.CaseOfNullableFloatArray();
                                        return;
                                    case TypeCode.Double:
                                        branch.CaseOfNullableDoubleArray();
                                        return;
                                    case TypeCode.DateTime:
                                        branch.CaseOfNullableDateTimeArray();
                                        return;
                                }
                                break;
                        }
                    }
                    else if (type.GenericTypeArguments.Length == 1)
                    {
                        switch (Type.GetTypeCode(type.GenericTypeArguments[0]))
                        {
                            case TypeCode.Boolean:
                                branch.CaseOfNullableBool();
                                return;
                            case TypeCode.Byte:
                                branch.CaseOfNullableUInt8();
                                return;
                            case TypeCode.UInt16:
                                branch.CaseOfNullableUInt16();
                                return;
                            case TypeCode.UInt32:
                                branch.CaseOfNullableUInt32();
                                return;
                            case TypeCode.UInt64:
                                branch.CaseOfNullableUInt64();
                                return;
                            case TypeCode.SByte:
                                branch.CaseOfNullableInt8();
                                return;
                            case TypeCode.Int16:
                                branch.CaseOfNullableInt16();
                                return;
                            case TypeCode.Int32:
                                branch.CaseOfNullableInt32();
                                return;
                            case TypeCode.Int64:
                                branch.CaseOfNullableInt64();
                                return;
                            case TypeCode.Single:
                                branch.CaseOfNullableFloat();
                                return;
                            case TypeCode.Double:
                                branch.CaseOfNullableDouble();
                                return;
                            case TypeCode.DateTime:
                                branch.CaseOfNullableDateTime();
                                return;
                        }
                    }
                    else if (type == typeof(object))
                    {
                        branch.CaseOfObject();
                        return;
                    }
                    break;
            }

            branch.CaseOfError();
        }
        catch (Exception e)
        {
            throw new TypeSwitcherException(type, e);
        }
    }

    /// <summary>
    /// Execute an action determination by type.
    /// The action is provided by the branch.
    /// </summary>
    /// <param name="type"></param>
    /// <param name="branch"></param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="TypeSwitcherException"></exception>
    [DebuggerStepThrough]
    public static void Execute(Design.ORiN3.Provider.V1.Type.ORiN3ValueType type, IValueTypeBranch branch)
    {
        branch = branch ?? throw new ArgumentNullException(nameof(branch));

        try
        {
            switch (type)
            {
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Bool:
                    branch.CaseOfBool();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3BoolArray:
                    branch.CaseOfBoolArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableBool:
                    branch.CaseOfNullableBool();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableBoolArray:
                    branch.CaseOfNullableBoolArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt8:
                    branch.CaseOfUInt8();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt8Array:
                    branch.CaseOfUInt8Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt8:
                    branch.CaseOfNullableUInt8();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt8Array:
                    branch.CaseOfNullableUInt8Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt16:
                    branch.CaseOfUInt16();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt16Array:
                    branch.CaseOfUInt16Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt16:
                    branch.CaseOfNullableUInt16();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt16Array:
                    branch.CaseOfNullableUInt16Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt32:
                    branch.CaseOfUInt32();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt32Array:
                    branch.CaseOfUInt32Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt32:
                    branch.CaseOfNullableUInt32();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt32Array:
                    branch.CaseOfNullableUInt32Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt64:
                    branch.CaseOfUInt64();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt64Array:
                    branch.CaseOfUInt64Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt64:
                    branch.CaseOfNullableUInt64();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt64Array:
                    branch.CaseOfNullableUInt64Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int8:
                    branch.CaseOfInt8();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int8Array:
                    branch.CaseOfInt8Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt8:
                    branch.CaseOfNullableInt8();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt8Array:
                    branch.CaseOfNullableInt8Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int16:
                    branch.CaseOfInt16();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int16Array:
                    branch.CaseOfInt16Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt16:
                    branch.CaseOfNullableInt16();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt16Array:
                    branch.CaseOfNullableInt16Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int32:
                    branch.CaseOfInt32();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int32Array:
                    branch.CaseOfInt32Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt32:
                    branch.CaseOfNullableInt32();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt32Array:
                    branch.CaseOfNullableInt32Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int64:
                    branch.CaseOfInt64();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int64Array:
                    branch.CaseOfInt64Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt64:
                    branch.CaseOfNullableInt64();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt64Array:
                    branch.CaseOfNullableInt64Array();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Float:
                    branch.CaseOfFloat();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3FloatArray:
                    branch.CaseOfFloatArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableFloat:
                    branch.CaseOfNullableFloat();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableFloatArray:
                    branch.CaseOfNullableFloatArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Double:
                    branch.CaseOfDouble();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3DoubleArray:
                    branch.CaseOfDoubleArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDouble:
                    branch.CaseOfNullableDouble();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDoubleArray:
                    branch.CaseOfNullableDoubleArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3String:
                    branch.CaseOfString();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3StringArray:
                    branch.CaseOfStringArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3DateTime:
                    branch.CaseOfDateTime();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3DateTimeArray:
                    branch.CaseOfDateTimeArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDateTime:
                    branch.CaseOfNullableDateTime();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDateTimeArray:
                    branch.CaseOfNullableDateTimeArray();
                    return;
                case Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Object:
                    branch.CaseOfObject();
                    return;
                default:
                    branch.CaseOfError();
                    return;
            }
        }
        catch (Exception e)
        {
            throw new TypeSwitcherException(type, e);
        }
    }

    /// <summary>
    /// Execute an action determination by type.
    /// The action is provided by the branch.
    /// </summary>
    /// <param name="type"></param>
    /// <param name="branch"></param>
    /// <returns></returns>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="TypeSwitcherException"></exception>
    [DebuggerStepThrough]
    public static Task ExecuteAsync(Design.ORiN3.Provider.V1.Type.ORiN3ValueType type, IValueTypeBranchAsync branch, CancellationToken token)
    {
        branch = branch ?? throw new ArgumentNullException(nameof(branch));

        try
        {
            return type switch
            {
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Bool => branch.CaseOfBoolAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3BoolArray => branch.CaseOfBoolArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableBool => branch.CaseOfNullableBoolAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableBoolArray => branch.CaseOfNullableBoolArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt8 => branch.CaseOfUInt8Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt8Array => branch.CaseOfUInt8ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt8 => branch.CaseOfNullableUInt8Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt8Array => branch.CaseOfNullableUInt8ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt16 => branch.CaseOfUInt16Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt16Array => branch.CaseOfUInt16ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt16 => branch.CaseOfNullableUInt16Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt16Array => branch.CaseOfNullableUInt16ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt32 => branch.CaseOfUInt32Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt32Array => branch.CaseOfUInt32ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt32 => branch.CaseOfNullableUInt32Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt32Array => branch.CaseOfNullableUInt32ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt64 => branch.CaseOfUInt64Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3UInt64Array => branch.CaseOfUInt64ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt64 => branch.CaseOfNullableUInt64Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableUInt64Array => branch.CaseOfNullableUInt64ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int8 => branch.CaseOfInt8Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int8Array => branch.CaseOfInt8ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt8 => branch.CaseOfNullableInt8Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt8Array => branch.CaseOfNullableInt8ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int16 => branch.CaseOfInt16Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int16Array => branch.CaseOfInt16ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt16 => branch.CaseOfNullableInt16Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt16Array => branch.CaseOfNullableInt16ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int32 => branch.CaseOfInt32Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int32Array => branch.CaseOfInt32ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt32 => branch.CaseOfNullableInt32Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt32Array => branch.CaseOfNullableInt32ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int64 => branch.CaseOfInt64Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Int64Array => branch.CaseOfInt64ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt64 => branch.CaseOfNullableInt64Async(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableInt64Array => branch.CaseOfNullableInt64ArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Float => branch.CaseOfFloatAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3FloatArray => branch.CaseOfFloatArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableFloat => branch.CaseOfNullableFloatAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableFloatArray => branch.CaseOfNullableFloatArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Double => branch.CaseOfDoubleAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3DoubleArray => branch.CaseOfDoubleArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDouble => branch.CaseOfNullableDoubleAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDoubleArray => branch.CaseOfNullableDoubleArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3String => branch.CaseOfStringAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3StringArray => branch.CaseOfStringArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3DateTime => branch.CaseOfDateTimeAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3DateTimeArray => branch.CaseOfDateTimeArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDateTime => branch.CaseOfNullableDateTimeAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3NullableDateTimeArray => branch.CaseOfNullableDateTimeArrayAsync(token),
                Design.ORiN3.Provider.V1.Type.ORiN3ValueType.ORiN3Object => branch.CaseOfObjectAsync(token),
                _ => branch.CaseOfErrorAsync(token),
            };
        }
        catch (Exception e)
        {
            throw new TypeSwitcherException(type, e);
        }
    }
}
