using Design.ORiN3.Common.V1;
using Design.ORiN3.Provider.V1.AutoGenerated;
using System.Collections.Generic;

namespace Message.ORiN3.Provider.Test.Mock
{
    internal class ValueBranchMock : IValueBranch
    {
        public List<ORiN3ValueType> History { get; private set; } = [];
        public bool IsNull { get; private set; } = false;

        public void CaseOfBool() { History.Add(ORiN3ValueType.Orin3Bool); }
        public void CaseOfBoolArray() { History.Add(ORiN3ValueType.Orin3BoolArray); }
        public void CaseOfNullableBoolArray() { History.Add(ORiN3ValueType.Orin3NullableBoolArray); }

        public void CaseOfInt8() { History.Add(ORiN3ValueType.Orin3Int8); }
        public void CaseOfInt8Array() { History.Add(ORiN3ValueType.Orin3Int8Array); }
        public void CaseOfNullableInt8Array() { History.Add(ORiN3ValueType.Orin3NullableInt8Array); }

        public void CaseOfInt16() { History.Add(ORiN3ValueType.Orin3Int16); }
        public void CaseOfInt16Array() { History.Add(ORiN3ValueType.Orin3Int16Array); }
        public void CaseOfNullableInt16Array() { History.Add(ORiN3ValueType.Orin3NullableInt16Array); }

        public void CaseOfInt32() { History.Add(ORiN3ValueType.Orin3Int32); }
        public void CaseOfInt32Array() { History.Add(ORiN3ValueType.Orin3Int32Array); }
        public void CaseOfNullableInt32Array() { History.Add(ORiN3ValueType.Orin3NullableInt32Array); }

        public void CaseOfInt64() { History.Add(ORiN3ValueType.Orin3Int64); }
        public void CaseOfInt64Array() { History.Add(ORiN3ValueType.Orin3Int64Array); }
        public void CaseOfNullableInt64Array() { History.Add(ORiN3ValueType.Orin3NullableInt64Array); }

        public void CaseOfUInt8() { History.Add(ORiN3ValueType.Orin3Uint8); }
        public void CaseOfUInt8Array() { History.Add(ORiN3ValueType.Orin3Uint8Array); }
        public void CaseOfNullableUInt8Array() { History.Add(ORiN3ValueType.Orin3NullableUint8Array); }

        public void CaseOfUInt16() { History.Add(ORiN3ValueType.Orin3Uint16); }
        public void CaseOfUInt16Array() { History.Add(ORiN3ValueType.Orin3Uint16Array); }
        public void CaseOfNullableUInt16Array() { History.Add(ORiN3ValueType.Orin3NullableUint16Array); }

        public void CaseOfUInt32() { History.Add(ORiN3ValueType.Orin3Uint32); }
        public void CaseOfUInt32Array() { History.Add(ORiN3ValueType.Orin3Uint32Array); }
        public void CaseOfNullableUInt32Array() { History.Add(ORiN3ValueType.Orin3NullableUint32Array); }

        public void CaseOfUInt64() { History.Add(ORiN3ValueType.Orin3Uint64); }
        public void CaseOfUInt64Array() { History.Add(ORiN3ValueType.Orin3Uint64Array); }
        public void CaseOfNullableUInt64Array() { History.Add(ORiN3ValueType.Orin3NullableUint64Array); }

        public void CaseOfFloat() { History.Add(ORiN3ValueType.Orin3Float); }
        public void CaseOfFloatArray() { History.Add(ORiN3ValueType.Orin3FloatArray); }
        public void CaseOfNullableFloatArray() { History.Add(ORiN3ValueType.Orin3NullableFloatArray); }

        public void CaseOfDouble() { History.Add(ORiN3ValueType.Orin3Double); }
        public void CaseOfDoubleArray() { History.Add(ORiN3ValueType.Orin3DoubleArray); }
        public void CaseOfNullableDoubleArray() { History.Add(ORiN3ValueType.Orin3NullableDoubleArray); }

        public void CaseOfDateTime() { History.Add(ORiN3ValueType.Orin3Datetime); }
        public void CaseOfDateTimeArray() { History.Add(ORiN3ValueType.Orin3DatetimeArray); }
        public void CaseOfNullableDateTimeArray() { History.Add(ORiN3ValueType.Orin3NullableDatetimeArray); }

        public void CaseOfString() { History.Add(ORiN3ValueType.Orin3String); }
        public void CaseOfStringArray() { History.Add(ORiN3ValueType.Orin3StringArray); }

        public void CaseOfNull() { History.Add(ORiN3ValueType.Orin3NullableBool); IsNull = true; }
        public void CaseOfObject() { History.Add(ORiN3ValueType.Orin3Object); }
    }
}
