using Xunit;
using MessageORiN3ObjectType = Message.ORiN3.Provider.V1.AutoGenerated.BaseObject.ORiN3ObjectType;
using DesignORiN3ObjectType = Design.ORiN3.Provider.V1.Type.ORiN3ObjectType;

namespace Message.ORiN3.Provider.Test.TestByDeveloper
{
    public class ORiN3ObjectTypeTest
    {
        [Fact]
        public void Test()
        {
            var messageORiN3ObjectTypes = Enum.GetValues<MessageORiN3ObjectType>()
                .ToDictionary(t => t.ToString().ToLower(), t => Convert.ToInt32(t));
            var designORiN3ObjectTypes = Enum.GetValues<DesignORiN3ObjectType>()
                .ToDictionary(t => t.ToString().ToLower(), t => Convert.ToInt32(t));

            foreach (var it in messageORiN3ObjectTypes)
            {
                Assert.True(designORiN3ObjectTypes.ContainsKey(it.Key));
                Assert.Equal(it.Value, designORiN3ObjectTypes[it.Key]);
            }
        }
    }
}